version: '3.5'

services:
 app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gql-test
    ports:
      - "3030:3030"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - API_URI=http://localhost:3030/api/apollo
    depends_on:
      db:
        condition: service_healthy

 db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

 
volumes:
 postgres-data: