import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import {ApolloWrapper} from "@/lib/apollo";
import Wrapper from "./wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className= {inter.className}>
        <ApolloWrapper>
          <Wrapper>
            <main className="w-[100svw] h-[100svh] overflow-hidden text-slate-800 bg-slate-100">
              {children}
            </main>
          </Wrapper>
        </ApolloWrapper>
      </body>
    </html>
  );
}
